### ISSUE TITLE
Problem deploying for FISCO-BCOS 3.5

### ISSUE THREAD

**Issue by tnkhanh** [WeBankBlockchain/WeIdentity-Build-Tools#242]
I'm following https://weidentity.readthedocs.io/zh-cn/latest/docs/weidentity-build-with-deploy.html to deploy (with Google Translate).
Versions used:
* fisco-bcos v3.5
* weid-build-tools-3.1.1-rc.1.jar

### Problem
* `./deploy.sh` reports missing `resources/conf`:
`./deploy.sh: line 109: cd: [..]/weid-build-tools/resources/conf: No such file or directory`
* After I create `resources/conf`:
`ERROR : fisco bcos version is 3.0. encrypt type is ECDSA, ca.crt, sdk.crt and sdk.key are needed.`
* After I copy missing files from `fisco/nodes/127.0.0.1/sdk` into `resources/conf` :
    ```
    Not found available log config(./clog.ini or ./conf/clog.ini), use the default configuration items
    Exception in thread "main" com.webank.weid.blockchain.exception.WeIdBaseException. Error code = 160007, Error message : the    ConfigOption build fail.
            at com.webank.weid.blockchain.service.fisco.server.v3.WeServerV3.initBcosSdk(WeServerV3.java:343)
            [...]
            at com.webank.weid.command.DeployContract.main(DeployContract.java:57)
    ```
* After I copy `run.config` to `clog.ini`:
    ```
    Exception in thread "main" com.webank.weid.blockchain.exception.WeIdBaseException. Error code = 160007, Error message : the ConfigOption build fail.                                                        
            at com.webank.weid.blockchain.service.fisco.server.v3.WeServerV3.initBcosSdk(WeServerV3.java:343)
            [...]
            at com.webank.weid.command.DeployContract.main(DeployContract.java:57)
    ```

    Here I'm stuck. What should I do to deploy? Is there updated docs?

**Comment by tnkhanh** [comment]
Sorry, I'm missing gradle. I will install gradle and report back
Edit: After installing gradle, everything is the same as before. What can I do now?

**Comment by tnkhanh** [comment]
Maybe because I'm missing MySQL. Let me install it and check

**Comment by tnkhanh** [comment]
I'm sticking to FISCO 2.9.1 and weid-build-tools 1.0.28 and they are working.
It looks like rc versions still have bugs
